spring:
  profiles:
    active: dev
    include: private
  servlet:
    multipart.max-file-size: 100MB
    multipart:
      max-request-size: 128MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./techtree_dev;MODE=MYSQL;TRACE_LEVEL_FILE=2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: NEED_TO_INPUT_ON_SECRET
            client-secret:
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/kakao/callback
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org:
      hibernate:
        orm.jdbc.bind: trace
        SQL: debug
        type: trace
